Repository commercelayer/mfe-cart, pull requests merged in 2025-03, with the labels that each got.

#94 Update PaymentMethod component to conditionally hide non-stripe payment sources
  packages/cart/src/components/Cart/Totals/ButtonCheckout.tsx
Labels: bug

#95 v4.1.1
  lerna.json
  packages/cart/package.json
Labels: ignore-for-release

#96 Update app dependencies and drop `@commercelayer/react-utils`
  package.json
  packages/cart/package.json
  packages/cart/src/components/CompanyLogo.tsx
  packages/cart/src/components/Footer.tsx
  packages/cart/src/components/InjectCssCustomProperties/hex2hsl.test.ts
  packages/cart/src/components/InjectCssCustomProperties/hex2hsl.ts
  packages/cart/src/components/InjectCssCustomProperties/index.tsx
  packages/cart/src/components/PageErrorLayout.tsx
  packages/cart/src/components/atoms/LogoCl.tsx
  packages/cart/src/pages/CartPage.tsx
  packages/cart/tailwind.config.js
  pnpm-lock.yaml
Labels: enhancement

#97 v4.1.2
  lerna.json
  package.json
  packages/cart/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#99 Refine buttons and use checkout url when using express payments
  package.json
  packages/cart/package.json
  packages/cart/src/assets/locales/it/common.json
  packages/cart/src/components/Cart/Totals/ButtonCheckout.tsx
  pnpm-lock.yaml
Labels: enhancement
